[phases.setup]
nixPkgs = ["chromium", "xvfb"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "playwright install --with-deps chromium"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "uvicorn app:app --host 0.0.0.0 --port $PORT" 