[phases.setup]
nixPkgs = ["chromium", "xvfb", "libxi6", "libgconf-2-4", "libnss3", "libatk-bridge2.0-0", "libdrm2", "libxkbcommon0", "libxcomposite1", "libxdamage1", "libxrandr2", "libgbm1", "libpango-1.0-0", "libcairo2", "libasound2"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "playwright install --with-deps chromium"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "uvicorn app:app --host 0.0.0.0 --port $PORT" 