services:
  - type: web
    name: trendyol-rag-system
    env: python
    buildCommand: |
      pip install -r requirements.txt
      apt-get update && apt-get install -y \
        wget \
        gnupg \
        unzip \
        xvfb \
        libxi6 \
        libgconf-2-4 \
        default-jdk \
        && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
        && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
        && apt-get update \
        && apt-get install -y google-chrome-stable \
        && rm -rf /var/lib/apt/lists/*
    startCommand: streamlit run comprehensive_rag_streamlit.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: CHROME_BIN
        value: /usr/bin/google-chrome
      - key: CHROME_DRIVER_PATH
        value: /usr/bin/chromedriver 